### ISSUE TITLE
Document the need to suffix ing secret with -conf

### ISSUE THREAD

**Issue by freshteapot** [math-nao/certs#36]
Firstly, thank you for making this cert :).

# What I think is the problem
It's not clear that the secretName used in the ingress needs to have the suffix "-conf".

```sh
        local SECRETNAME=$(echo ${input} | jq -rc '.secretName')
```
https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L210

I had my ingress setup with a secretName called ["tls"](https://github.com/freshteapot/learnalist-api/blob/master/k8s/learnalist.yaml#L82).

# Solution
- Make a note in the README it needs the suffix.

# Reference
- [code sets -conf suffix](https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L210)
- [code without suffix](https://github.com/freshteapot/learnalist-api/blob/master/k8s/learnalist.yaml#L82)

**Comment by freshteapot** [comment]
I am actually not sure what the problem is. Which has me thinking its user error (ie my fault).

I had to do it manually via acme.sh.

I will investigate more.

**Comment by freshteapot** [comment]
# Conclusion
- Nothing wrong with the suffix.
- Issue was linked to one tls supporting multiple domains

## This does not work
```yaml
  tls:
    - secretName: tls
      hosts:
        - lal01.learnalist.net
        - learnalist.net
```

## This works
```yaml
  tls:
    - secretName: tls-learnalist
      hosts:
        - learnalist.net
    - secretName: tls-learnalist-lal01
      hosts:
        - lal01.learnalist.net
```
